### ISSUE TITLE
font size

### ISSUE THREAD

**Issue by tsukinousagis** [shudesigns/olddashfont#4]
the font size doesn't seem to change anymore :(

**Comment by shudesigns** [comment]
I just checked and it's working as expected. Please check if your browser/extension is up to date, or if there's any other extension you're using that is conflicting with this one.

**Comment by tsukinousagis** [comment]
***@***.******@***.***D769DA.AA62D5F0]

I tried changing the font size in the code but it changed everything except the post font which is still big. I don’t have any other extensions other than xkit

De: Shu-Wei ***@***.***>
Enviado: Friday, 25 June 2021 15:39
Para: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Assunto: Re: [shudesigns/olddashfont] font size (#4)


I just checked and it's working as expected. Please check if your browser/extension is up to date, or if there's any other extension you're using that is conflicting with this one.
